// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBH7ApHYrlecRDE-mZ9t2gBukQ_2Dhog0',
    appId: '1:177240696767:web:2970dcba0bc6e058e9e30a',
    messagingSenderId: '177240696767',
    projectId: 'dummyauthn',
    authDomain: 'dummyauthn.firebaseapp.com',
    storageBucket: 'dummyauthn.firebasestorage.app',
    measurementId: 'G-NZ1XT3TZLX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmh7v7mRVP0qGNGn-KLoZp-IUPO43lmqg',
    appId: '1:177240696767:ios:c437e83ed6598097e9e30a',
    messagingSenderId: '177240696767',
    projectId: 'dummyauthn',
    storageBucket: 'dummyauthn.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmh7v7mRVP0qGNGn-KLoZp-IUPO43lmqg',
    appId: '1:177240696767:ios:c437e83ed6598097e9e30a',
    messagingSenderId: '177240696767',
    projectId: 'dummyauthn',
    storageBucket: 'dummyauthn.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBH7ApHYrlecRDE-mZ9t2gBukQ_2Dhog0',
    appId: '1:177240696767:web:94bb16cc01d2f9b6e9e30a',
    messagingSenderId: '177240696767',
    projectId: 'dummyauthn',
    authDomain: 'dummyauthn.firebaseapp.com',
    storageBucket: 'dummyauthn.firebasestorage.app',
    measurementId: 'G-E97P2SBEN5',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh_JqjVpEJPqEfgy4oAM_eNkfQTaAV-g4',
    appId: '1:177240696767:android:a7b187455d0f3309e9e30a',
    messagingSenderId: '177240696767',
    projectId: 'dummyauthn',
    storageBucket: 'dummyauthn.firebasestorage.app',
  );
}
